---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: demo
  namespace: demo
  labels:
    app: demo

spec:
  replicas: 9
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      name: demo
      labels:
        app: demo
    spec:
      containers:
      - name: echo-demo
        image: kureikain/echo
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
