# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Our custom box with pre-configured k8s and vagrant
  # Provison 3 nodes cluster

  # First node is master
  config.vm.define "master" do |node|
    node.vm.hostname = "master.dev"
    node.vm.network "private_network", ip: "10.9.0.2"
    node.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      node.vm.box = "kureikain/k8s-cni-strongswan-master"
      # Give it more RAM since master run lots of stuff
      vb.customize ["modifyvm", :id, "--memory", "1536"]
    end
  end

  2.times do |i|
    config.vm.define "minion#{i+1}" do |node|
      node.vm.hostname = "minion-#{i+1}.dev"
      node.vm.network "private_network", ip: "10.9.0.#{3+i}"

      node.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        node.vm.box = "kureikain/k8s-cni-strongswan-node"
        vb.customize ["modifyvm", :id, "--memory", "512"]
      end
    end
  end
end
