# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/xenial64"

  3.times do |i|
    config.vm.define "n#{i+1}" do |node|
      node.vm.box = "ubuntu/xenial64"
      node.vm.network "private_network", ip: "10.9.0.#{2+i}"
      node.vm.provider "virtualbox" do |vb|
        # Use VBoxManage to customize the VM. For example to change memory:
        vb.customize ["modifyvm", :id, "--memory", "256"]
      end
    end
  end
end
